version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8082:8082"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
