version: '3'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - mongodb+srv://ritya:0330@cluster0.ad1ju.mongodb.net/doctor
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
