version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
